import React, { createContext , useContext, useState} from "react";

const EventContext = createContext([]);

export const EventProvider = ({children}) => {
    const [events] = useState([
        {
            id: 1,
            imageSrc: require("../../images/event1.jpg"),
            title: "Nature Retreat: Wilderness Adventure",
            guestCount: 73,
            amount: "249.99",
            date: "June 12, 2023",
            venue: "Wilderness Camp",
            foodServed: "Campfire Cooking",
            extras: "Guided wildlife tours",
            extraAmount: 45.0,
            eventDescription:
              "Escape to the great outdoors with our Nature Retreat. Experience campfire cooking, guided wildlife tours, and the tranquility of the wilderness. Connect with nature and rejuvenate your spirit.",
            eventDuration: "3 days and 2 nights",
            registrationDeadline: "May 30, 2023",
            availability: "Limited spots available",
            paymentOptions: ["Credit Card", "Bank Transfer"],
            bookNow: "/book-info/1",
          },
          {
            id: 2,
            imageSrc: require("../../images/event2.jpg"),
            title: "Glamorous Wedding Extravaganza",
            guestCount: 268,
            amount: "4999.99",
            date: "September 8, 2023",
            venue: "Luxury Wedding Hall",
            foodServed: "Exquisite Wedding Banquet",
            extras: "Professional photography and videography",
            extraAmount: 500.0,
            eventDescription:
              "Join us for the most glamorous wedding of the year. Experience an exquisite wedding banquet, capture every moment with professional photography and videography, and witness the union of two hearts.",
            eventDuration: "10:00 AM - 11:00 PM",
            registrationDeadline: "August 15, 2023",
            availability: "Limited seats remaining",
            paymentOptions: ["Credit Card", "Online Bank Transfer"],
            bookNow: "/book-info/2",
          },
          {
            id: 3,
            imageSrc: require("../../images/event3.jpg"),
            title: "International Tech Summit",
            guestCount: 152,
            amount: "299.99",
            date: "November 20, 2023",
            venue: "Tech Summit Center",
            foodServed: "Global Cuisine",
            extras: "Keynote speeches and panel discussions",
            extraAmount: 25.0,
            eventDescription:
              "Join us at the International Tech Summit, where tech leaders from around the world converge. Enjoy global cuisine, listen to inspiring keynote speeches, and participate in engaging panel discussions.",
            eventDuration: "8:00 AM - 6:00 PM",
            registrationDeadline: "October 31, 2023",
            availability: "Open for all",
            paymentOptions: ["Credit Card", "Cryptocurrency"],
            bookNow: "/book-info/3",
          },
          {
            id: 4,
            imageSrc: require("../../images/event4.jpg"),
            title: "Princess-themed Birthday Party",
            guestCount: 245,
            amount: "199.99",
            date: "July 8, 2023",
            venue: "Royal Palace",
            foodServed: "Royal Feast",
            extras: "Princess dress-up and entertainment",
            extraAmount: 20.0,
            eventDescription:
              "Make your child's dreams come true with our Princess-themed Birthday Party. Indulge in a royal feast, let the kids dress up as their favorite princesses, and enjoy enchanting entertainment fit for royalty.",
            eventDuration: "2:00 PM - 6:00 PM",
            registrationDeadline: "June 20, 2023",
            availability: "Limited slots available",
            paymentOptions: ["Credit Card", "PayPal"],
            bookNow: "/book-info/4",
          },
          {
            id: 5,
            imageSrc: require("../../images/event5.jpg"),
            title: "Corporate Conference 2023",
            guestCount: 189,
            amount: "399.99",
            date: "August 15, 2023",
            venue: "Business Convention Center",
            foodServed: "Business Lunch",
            extras: "Workshops and networking sessions",
            extraAmount: 30.0,
            eventDescription:
              "Join us at the Corporate Conference 2023 for a day of business insights. Enjoy a business lunch, attend workshops, and network with industry leaders and professionals.",
            eventDuration: "9:00 AM - 5:00 PM",
            registrationDeadline: "August 1, 2023",
            availability: "Open for corporate registrations",
            paymentOptions: ["Credit Card", "Wire Transfer"],
            bookNow: "/book-info/5",
          },
          {
            id: 6,
            imageSrc: require("../../images/event6.jpg"),
            title: "Rock 'n' Roll Birthday Bash",
            guestCount: 327,
            amount: "79.99",
            date: "April 5, 2023",
            venue: "Rockin' Party Hall",
            foodServed: "Rock 'n' Roll Snacks",
            extras: "Live rock band and karaoke",
            extraAmount: 15.0,
            eventDescription:
              "Get ready to rock and roll at our birthday bash! Enjoy rock 'n' roll snacks, dance to a live rock band, and unleash your inner rockstar with karaoke. It's a night of music and fun.",
            eventDuration: "7:00 PM - 12:00 AM",
            registrationDeadline: "March 20, 2023",
            availability: "Limited tickets remaining",
            paymentOptions: ["Credit Card", "Venmo"],
            bookNow: "/book-info/6",
          },
          {
            id: 7,
            imageSrc: require("../../images/event1.jpg"),
            title: "Art Expo: A Celebration of Creativity",
            guestCount: 319,
            amount: "49.99",
            date: "October 1, 2023",
            venue: "Art Gallery",
            foodServed: "Artistic Finger Foods",
            extras: "Live art demonstrations",
            extraAmount: 10.0,
            eventDescription:
              "Explore the world of art at our Art Expo. Savor artistic finger foods, witness live art demonstrations, and celebrate creativity in all its forms. It's an art lover's paradise.",
            eventDuration: "11:00 AM - 4:00 PM",
            registrationDeadline: "September 15, 2023",
            availability: "Open for art enthusiasts",
            paymentOptions: ["Credit Card", "Art Tokens"],
            bookNow: "/book-info/7",
          },
          {
            id: 8,
            imageSrc: require("../../images/event2.jpg"),
            title: "Business Networking Breakfast",
            guestCount: 241,
            amount: "29.99",
            date: "May 10, 2023",
            venue: "Business Cafe",
            foodServed: "Continental Breakfast",
            extras: "Networking sessions and guest speakers",
            extraAmount: 5.0,
            eventDescription:
              "Join us for a morning of business networking over a delicious continental breakfast. Connect with fellow professionals, engage in networking sessions, and gain insights from guest speakers.",
            eventDuration: "8:30 AM - 11:00 AM",
            registrationDeadline: "April 30, 2023",
            availability: "Open for business professionals",
            paymentOptions: ["Credit Card", "Business Expense"],
            bookNow: "/book-info/8",
          },
          {
            id: 9,
            imageSrc: require("../../images/event3.jpg"),
            title: "Masquerade Ball: Midnight Mystery",
            guestCount: 156,
            amount: "199.99",
            date: "December 31, 2023",
            venue: "Grand Masquerade Hall",
            foodServed: "Gourmet Masquerade Buffet",
            extras: "Mask design contest and fireworks",
            extraAmount: 25.0,
            eventDescription:
              "Ring in the New Year at our Masquerade Ball: Midnight Mystery. Enjoy a gourmet masquerade buffet, participate in a mask design contest, and watch the skies light up with a spectacular fireworks display.",
            eventDuration: "9:00 PM - 2:00 AM",
            registrationDeadline: "December 15, 2023",
            availability: "Limited masks available",
            paymentOptions: ["Credit Card", "PayPal"],
            bookNow: "/book-info/9",
          },
          {
            id: 10,
            imageSrc: require("../../images/event4.jpg"),
            title: "Family Fun Day at the Park",
            guestCount: 42,
            amount: "19.99",
            date: "July 1, 2023",
            venue: "City Park",
            foodServed: "Picnic in the Park",
            extras: "Games and family activities",
            extraAmount: 5.0,
            eventDescription:
              "Join us for a day of family fun at the City Park. Enjoy a picnic in the park, play games, and engage in family activities. It's a perfect day to create lasting memories.",
            eventDuration: "10:00 AM - 4:00 PM",
            registrationDeadline: "June 20, 2023",
            availability: "Open for families",
            paymentOptions: ["Cash", "Online Payment"],
            bookNow: "/book-info/10",
          },
          {
            id: 11,
            imageSrc: require("../../images/event5.jpg"),
            title: "Safari Serenade: A Night in the Savanna",
            guestCount: 273,
            amount: "99.99",
            date: "October 15, 2023",
            venue: "Savanna Oasis",
            foodServed: "African Buffet Feast",
            extras: "Includes traditional music and dance",
            extraAmount: 20.0,
            eventDescription:
              "Experience the heart of Africa with Safari Serenade. Join us for a night in the wild Savanna, featuring an authentic African buffet feast, traditional music, and dance performances under the starry African sky.",
            eventDuration: "6:00 PM - 11:00 PM",
            registrationDeadline: "October 1, 2023",
            availability: "Limited spots available",
            paymentOptions: ["Credit Card", "Mobile Money"],
            bookNow: "/book-info/11",
          },
          {
            id: 12,
            imageSrc: require("../../images/event2.jpg"),
            title: "Kente Gala: A Night of Colorful Elegance",
            guestCount: 124,
            amount: "149.99",
            date: "November 5, 2023",
            venue: "Kente Grand Hall",
            foodServed: "Exquisite African Cuisine",
            extras: "Includes traditional attire showcase",
            extraAmount: 30.0,
            eventDescription:
              "Embrace the rich tapestry of African culture at Kente Gala. Indulge in exquisite African cuisine, dance to live African rhythms, and witness a showcase of vibrant traditional attire from across the continent.",
            eventDuration: "7:00 PM - 1:00 AM",
            registrationDeadline: "October 25, 2023",
            availability: "Limited tickets available",
            paymentOptions: ["Credit Card", "African Mobile Wallets"],
            bookNow: "/book-info/12",
          },
    ]);

    return <EventContext.Provider value={{ events }}> {children} </EventContext.Provider>
};

export const useEvent = () => {
    const context = useContext(EventContext);
    if (!context) {
      throw new Error("useEvent must be used within an EventProvider");
    }
    return context;
};